version: "3"
services:
  server:
    #########################
    #  Setup node container #
    #########################
    container_name: server
    build:
      context: ./server
    environment:
      - API_HOST=http://localhost:3001
    ports:
      - "3001:3001"
    volumes:
      - ./server/src:./server
    command: "npm start"


    ############################
    #  Setup client container  #
    ############################
  client:
    container_name: client
    build: ./client
    environment:
      - API_HOST=http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./client/src:./client
    links:
      - server
    command: "npm start"
